packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/plugin-react-swc/playground/**'
  - 'packages/plugin-rsc/examples/*'

catalogs:
  rolldown-vite:
    vite: https://pkg.pr.new/vitejs/rolldown-vite@318
